name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Cambiar "main" por la rama principal de tu repositorio

jobs:
  build:

  runs-on: ubuntu-latest
  permissions:
    contents: read
    packages: write



  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        # Comandos para compilar tu proyecto aquí
        # Ejemplo: npm install o mvn package

    - name: Test
      run: |
        # Comandos para ejecutar pruebas aquí
        # Ejemplo: npm test o mvn test

    - name: Security Scan
      run: |
        # Comandos para escanear el código en busca de vulnerabilidades
        # Ejemplo: npm audit o trivy

  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: |
        # Comandos para construir la imagen de Docker
        # Ejemplo: docker build -t usuario/nombre-imagen:etiqueta .

    - name: Push Docker Image
      run: |
        # Comando para subir la imagen de Docker a Docker Hub
        # Ejemplo: docker push usuario/nombre-imagen:etiqueta

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      run: |
        # Comandos para implementar o desplegar la aplicación en el servidor
        # Puedes utilizar scripts personalizados o herramientas de despliegue como Ansible o SSH

